;;; consult-project-extra-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-project-extra.el

(autoload 'consult-project-extra-project-fn "consult-project-extra" "\
`consult-project-extra' version of `consult--default-project-function'.

Return project root directory.
When no project is found and MAY-PROMPT is non-nil ask the user.

(fn &optional MAY-PROMPT)" t)
(autoload 'consult-project-extra-find "consult-project-extra" "\
Create an endpoint for accessing different project sources.
The consult view can be narrowed to: (b) current project's
buffers,(f) current project's files and (p) to select from the
list of known projects.

If `consult-project-extra-find' is called outside of an project,
the user is queried for a project via `consult-project-function'
before `consult-project-extra-find' is called on that project

A different action is issued depending on the source. For both
buffers and project files, the default action is to visit the
selected element. When a known project is selected,
`consult-project-function' is called recursively with the
selected project as ROOT.

When OTHER-WINDOW is non-nil open the selected buffer in another
window.

When called Interactively PREFIX sets OTHER-WINDOW.

(fn &optional ROOT OTHER-WINDOW)" t)
(autoload 'consult-project-extra-find-other-window "consult-project-extra" "\
Variant of `consult-project-extra' which opens in a second window." t)
(register-definition-prefixes "consult-project-extra" '("consult-project-extra-"))

;;; End of scraped data

(provide 'consult-project-extra-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-project-extra-autoloads.el ends here
